#!/bin/bash
#
# Runs the mkPortMux.sh script for each CPU variant file in the include/pio/ folder.
# For Ubuntu systems, that folder is given below.  For any other platforms, some
# changes to these scripts are probably necessary.
#
# This script should be run in the folder containing SAMD51_Dumpster.h.
#
# This script emits one include file for each CPU variant file found in the include/pio
# folder, and the file named "portmux.h", which includes each of the CPU variant files.
# SAMD51_Dumpster.h includes portmux.h, so most users will not even know these files
# exist, much less subject themselves to the trauma of figuring out what they do.
#
# If you are fastidious about keeping everything up-to-date, you should run these scripts
# every time you you update the Arduino boards package for the SAMD51 board you use.  After
# running this script, you may want to restart Arduino, just to make sure it picks up the
# updated header files.

date_time=$(date '+%Y%m%d_%H%M%S_%N' )
date_time2=$(date '+%Y-%m-%d %H:%M:%S %Z' )
file_root=/tmp/portmuxall_${date_time}
file_tmp1=${file_root}_tmp1
file_awk1=${file_root}_awk1

output_file="portmux.h"

pio_folder=~/.arduino15/packages/adafruit/tools/CMSIS-Atmel/1.2.2/CMSIS/Device/ATMEL/samd51/include/pio

cat > "${file_tmp1}" <<EOF1
/*
 * DO NOT EDIT!  This file was automatically generated by mkAllPortMux.sh
 * ${date_time2}
 */
 
#ifndef _MKALLPORTMUX_SH_
#define _MKALLPORTMUX_SH_

EOF1

files=$(cd "${pio_folder}" ; ls samd51*.h )

for fname in $files ; do
  echo "Processing ${fname}"
  
  infile="${pio_folder}/${fname}"
  ./mkPortMux.sh "${infile}" > "${fname}"
  
  echo "#include \"${fname}\"" >> "${file_tmp1}"
  
done

cat >> "${file_tmp1}" <<EOF2

#endif // _MKALLPORTMUX_SH_

EOF2

cp "${file_tmp1}" "${output_file}"
