/*
 * DO NOT EDIT!  This file was automatically generated by mkAllPortMux.sh
 * 2024-02-08 19:24:06 PST
 */
 
#ifndef _MKALLPORTMUX_SH_
#define _MKALLPORTMUX_SH_

#include "samd51g18a.h"
#include "samd51g19a.h"
#include "samd51j18a.h"
#include "samd51j19a.h"
#include "samd51j20a.h"
#include "samd51n19a.h"
#include "samd51n20a.h"
#include "samd51p19a.h"
#include "samd51p20a.h"

#endif // _MKALLPORTMUX_SH_

